[env:esp32gateway]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D GATEWAY_ID=\"LG-GW01\"

lib_deps = 
    sandeepmistry/LoRa @ ^0.8.0
    bblanchon/ArduinoJson @ ^7.0.4
